project:
  project_id: mulcahy-testproject
  project_number: 616654894457
  location: global

storage:
  output_bucket : upload-proje
  input_bucket : upload-proje
  
db:
  video: metadata
  image: images
  audio: audio
  article: article-demo

search:
  index_endpoint: vector_search_endpoint_id
  deployed_index_id: vector_search_id

models:
  embedding: text-embedding-004
  creation: gemini-1.5-pro-001
  
