project:
  project_id: your_project_id
  project_number: 123456789101
  location: global

storage:
  output_bucket : your-project-id-media-output
  input_bucket : your-project-id-media-input
  
db:
  video: metadata
  image: images
  audio: audio
  article: article-demo

search:
  index_endpoint: vector_search_endpoint_id
  deployed_index_id: vector_search_id

models:
  embedding: text-embedding-004
  creation: gemini-1.5-pro-001
  